#!/usr/bin/env python3
"""Genera sitemap.xml a partir de los HTML publicables.

    python tools/make-sitemap.py            # reescribe sitemap.xml
    python tools/make-sitemap.py --check    # sólo informa si quedó viejo

POR QUÉ UN SCRIPT Y NO A MANO. El sitemap es una lista duplicada: las mismas
URLs que ya están en el sistema de archivos, escritas otra vez. Igual que el nav
y el footer, la duplicación se banca sólo si está vigilada — pero acá hay algo
mejor que vigilarla, que es no escribirla: las páginas ya existen como
directorios con su index.html, así que la lista se deriva. Agregar una página
nueva es correr esto; y si alguien se olvida, `check-structure.py` lo caza,
porque verifica que toda página publicable esté en el sitemap.

SIN <lastmod> A PROPÓSITO. Es opcional, y sólo sirve si es exacto: un lastmod
que miente es peor que ninguno, porque los buscadores dejan de creerle al
archivo entero. Para que fuera exacto habría que sacarlo de git en cada
regeneración, y entonces el sitemap cambiaría en cada commit ensuciando el
historial. Con ocho páginas estáticas no compensa. <changefreq> y <priority>
directamente los ignora Google desde hace años.

La 404 queda afuera: pedirle a un buscador que indexe la página de error es
exactamente lo contrario de lo que hace falta.
"""
import re
import sys
from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent
SITIO = "https://kotodamafinance.com"
SALIDA = RAIZ / "sitemap.xml"
EXCLUIDOS = {"_dev", "_ref", ".git", "docs", "tools", "node_modules"}
NO_INDEXABLES = {"404.html"}
# Una página que declara noindex queda FUERA del sitemap, y se deriva de la
# propia página en vez de mantener una lista acá: listar una página noindex
# es una contradicción que check-structure ya caza, y la lista a mano sería
# una segunda fuente de verdad. Caso que motivó la regla (2026-08-07): el
# andamiaje de seguros lleva noindex mientras sea placeholder — al redactar
# se saca la meta y ESTE script vuelve a listarla solo.
RE_NOINDEX = re.compile(r'<meta name="robots"[^>]*noindex')

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass


def urls():
    """URLs canónicas, en el mismo esquema por directorios que usa el sitio:
    /musubi/ y no /musubi/index.html."""
    encontradas = []
    for p in sorted(RAIZ.rglob("*.html")):
        rel = p.relative_to(RAIZ)
        if any(parte in EXCLUIDOS for parte in rel.parts):
            continue
        if rel.as_posix() in NO_INDEXABLES:
            continue
        if RE_NOINDEX.search(p.read_text(encoding="utf-8")):
            continue
        if p.name == "index.html":
            carpeta = rel.parent.as_posix()
            encontradas.append("/" if carpeta == "." else f"/{carpeta}/")
        else:
            encontradas.append("/" + rel.as_posix())
    # la portada primero, el resto alfabético
    return sorted(set(encontradas), key=lambda u: (u != "/", u))


def documento():
    cuerpo = "\n".join(f"  <url><loc>{SITIO}{u}</loc></url>" for u in urls())
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            # EN INGLÉS, aunque el resto de este script esté en castellano: el
            # comentario viaja DENTRO del sitemap, y un sitemap no tiene versión
            # renderizada — quien abre /sitemap.xml lo ve tal cual. Es superficie
            # publicada, no anotación interna.
            '<!-- Generated by tools/make-sitemap.py — do not edit by hand.\n'
            '     check-structure.py verifies that no page is missing. -->\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            f"{cuerpo}\n"
            "</urlset>\n")


def main():
    nuevo = documento()
    if "--check" in sys.argv:
        viejo = SALIDA.read_text(encoding="utf-8") if SALIDA.exists() else ""
        if viejo == nuevo:
            print(f"  sitemap.xml al día ({len(urls())} URLs)")
            return 0
        print("  sitemap.xml quedó viejo -> correr: python tools/make-sitemap.py")
        return 1
    SALIDA.write_text(nuevo, encoding="utf-8")
    for u in urls():
        print(f"  {SITIO}{u}")
    print(f"{len(urls())} URLs en sitemap.xml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
